Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/08/2022
Var
num,resultado,contador:inteiro


Inicio
escreval ("digite um numero: ")
leia (num)


para contador de 1 ate 10 faca
resultado <- num*contador

escreval (num," x ",contador," = ",resultado)





fimpara


Fimalgoritmo