algoritmo "semnome"
// Função :
// Autor :
// Data : 01/11/2022
// Seção de Declarações
var
numero: vetor [1..15]  de inteiro
contador,soma:inteiro
inicio
// Seção de Comandos

para contador de 1 ate 15 faca
escreval ("digite um numero")
leia (numero[contador])

fimpara
escreval("os numeros positivos são")

para contador de 1 ate 15 faca
se numero[contador]>0 entao
escreval (numero[contador])
fimse
fimpara

fimalgoritmo