algoritmo "1- Faça um algoritmo que escreva na tela os números de um número inicial a um número final. Os números inicial e final devem ser informados pelo usuário."

var
 contador,inicial,final:inteiro
inicio

escreval ("digite um numero: ")
 leia (inicial)


escreval ("digite um numero: ")
 leia (final)

para contador de inicial ate final faca



escreval (contador)
 fimpara
fimalgoritmo
