algoritmo "semnome"
// Função :
// Autor :
// Data : 03/05/2022
// Seção de Declarações 
var
n1,n1,n3,n4:real
total:real
inicio
// Seção de Comandos 
escreval("digite um valor e atribua para  n1:")
leia(n1)
escreval("digite um valor e atribua para  n2:")
leia(n2)
escreval("digite um valor e atribua para  n3:")
leia(n3)
escreval("digite um valor e atribua para  n4:")
leia(n4)
total<-(n1*n1)+(n2*n2)+(n3*n3)+(n4*n4)
escreval("o total é : ",total)
fimalgoritmo
