algoritmo "semnome"
// Função :
// Autor :
// Data : 01/08/2022
// Seção de Declarações 
var
idade:inteiro
altura:real
inicio
escreval("digite sua idade:")
leia (idade)
escreval ("digite sua altura:")
  leia (altura)
  
se ((idade>= 18) e (altura>= 1.75))   entao
    escreval("voce pode participar do campeonato de volei!")
    
    senao
    
    escreval ("sua altura ou idade e insuficiente!")

fimse
escreval("acabou o  prorama!")



fimalgoritmo

